### ISSUE TITLE
There was a problem sending the request to the wallet

### ISSUE THREAD

**Issue by nomantariq18** [cryptean/bitcoinlib#74] opened 2018-03-15 08:19 UTC
i'm using BitcoinLib. when i run my code this error occurs "There was a problem sending the request to the wallet"
My webconfig code is 
```
 <add key="Bitcoin_DaemonUrl" value="http://localhost:8332" />
    <add key="Bitcoin_DaemonUrl_Testnet" value="http://localhost:18332" />
    <add key="Bitcoin_WalletPassword" value="MyWalletPassword" />
    <add key="Bitcoin_RpcUsername" value="MyRpcUsername" />
    <add key="Bitcoin_RpcPassword" value="MyRpcPassword" />
```

**Comment by moodmosaic** [comment] 2018-03-15 09:10
It looks like you can't send HTTP requests to Bitcoin Core(?) Do you have `server=1` and `rpcport=8332` in your `bitcoin.conf` file?

**Comment by nomantariq18** [comment] 2018-03-15 09:16
in bitcoin.conf that is my code 

rpcuser = MyRpcUsername
rpcpassword = MyRpcPassword
server=1
txindex=1

**Comment by moodmosaic** [comment] 2018-03-15 09:29
It tells you that it can't connect to localhost. Perhaps some firewall issue(s)?

**Comment by nomantariq18** [comment] 2018-03-15 09:33
i have turned off window firewall but sitll that issue

**Comment by moodmosaic** [comment] 2018-09-05 11:34
Closing this as non-reproducible. Feel free to reopen it or add comments to it.

**Closed by moodmosaic** 2018-09-05 11:34 UTC
Labels: question
