### ISSUE TITLE
It produces errors with bitcoin core 0.17.1

### ISSUE THREAD

**Issue by psun888** [cryptean/bitcoinlib#102] opened 2019-01-06 17:58 UTC
When using the latest bitcoin core 0.17.1, it produces 500 server error, and bitcoin core version 0.16.3 works without any issue.

**Comment by psun888** [comment] 2019-01-06 19:35
Here is the detailed error:

BitcoinLib.ExceptionHandling.Rpc.RpcInternalServerErrorException: dummy first argument must be excluded or set to "*". ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at BitcoinLib.RPC.Connector.RpcConnector.MakeRequest[T](RpcMethods rpcMethod, Object[] parameters) in C:\bitcoinlib-master\src\BitcoinLib\RPC\Connector\RpcConnector.cs:line 57
   --- End of inner exception stack trace ---
   at BitcoinLib.RPC.Connector.RpcConnector.MakeRequest[T](RpcMethods rpcMethod, Object[] parameters) in C:\bitcoinlib-master\src\BitcoinLib\RPC\Connector\RpcConnector.cs:line 106
   at BitcoinLib.Services.CoinService.GetBalance(String account, Int32 minConf, Nullable`1 includeWatchonly) in C:\bitcoinlib-master\src\BitcoinLib\Services\RpcServices\RpcService\RpcService.cs:line 148

**Comment by moodmosaic** [comment] 2019-01-07 07:15
Just to make sure we know exactly where to troubleshoot, this isn't the case with 0.17.0 either, right?

**Comment by psun888** [comment] 2019-01-07 07:34
I tested 0.17.0, not working either. Only version 0.16.3 or lower versions are working. thanks

**Comment by moodmosaic** [comment] 2019-01-08 21:59
I just used the demo app with 0.17.0 and 0.17.1, and run it up to GetBalance where you seem to be getting the error and it works fine:

```
Connecting to Bitcoin TestNet via RPC at http://localhost:18332...[OK]

Bitcoin Network Difficulty: 13,279,725

My balance: 0.00000000 BTC
Current block: 1,451,550
```

In Bitcoin Core, go to *Settings*, in the *Main* tab click on the *Open Configuration File button* and make sure your `bitcoin.conf` looks like this:

```
rpcuser = MyRpcUsername
rpcpassword = MyRpcPassword
server=1
txindex=1
```

The BitcoinLib version I used to test this is [1.12.0](https://www.nuget.org/packages/BitcoinLib/1.12.0).

---

Closing this as I can't seem to reproduce it. Feel free to reopen it or add comments to it. Thank you for your feedback!

**Closed by moodmosaic** 2019-01-08 21:59 UTC
